name: Scrape XMPro Blogs and Commit

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI
  #schedule:
    #- cron: '0 0 * * *'  # Runs at midnight UTC every day

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install requests
      - name: Run script
        run: python scripts/scrape-xmpro-blogs.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update transcripts" || echo "No changes to commit"
          git push
